### ISSUE TITLE
Jupyter Kernel stopped working with latest versions of cadabra2

### ISSUE THREAD

**Issue by inaki-ortizdelandaluce** [Dustpancake/cadabra-resources#1] opened 2024-07-28 21:08 UTC
First of all, many thanks for making this repo available, it's been of great help. 

I have tried to use your Dockerfile as is for the latest commits in the master branch of the cadabra2 repository and apparently everything goes fine but, when executing the cells in the jupyter notebook, I get the following error in the cadabra2_defaults.py module:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cadabra2_jupyter/kernel.py", line 56, in do_execute
    self._execute_python(pycode)
  File "/usr/local/lib/python3.10/site-packages/cadabra2_jupyter/kernel.py", line 110, in _execute_python
    self._sandbox_context(pycode)
  File "/usr/local/lib/python3.10/site-packages/cadabra2_jupyter/context.py", line 51, in __call__
    exec(code, self._sandbox)
  File "<string>", line 1, in <module>
  File "cadabra2_defaults.py", line 275, in display
    id=server.send(ret, "latex_view", 0, cell_id, False)
TypeError: Server.send() takes 5 positional arguments but 6 were given
```
I guess some python method signatures have changed and therefore the error, but I ignore how to fix it. I initially thought commenting out the disabling of the client_server build in the Dockerfile could fix it, but I didn't succeed.

As a workaround, I have managed to get it working cloning an old tag from April 18:
```
RUN git clone --branch 2.4.5.6 --depth 1 https://github.com/kpeeters/cadabra2
```

**Comment by fjebaker** [comment] 2024-07-28 22:13
Hi @inaki-ortizdelandaluce thanks for opening the issue and including the tracebacks. I am able to reproduce the issue.

If I compare the version of cadabra2 that you identified as working (2.4.5.6) to the master branch I see there were API changes made, e.g.

```diff
-        def send(self, data, typestr, parent_id, last_in_sequence):
+        def send(self, data, typestr, parent_id, cell_id, last_in_sequence):
```

The traceback we get is a bit of a red herring because it's pointing to the wrong file as the culprit.

The global instance of the `server` that it is calling `send` on is given to the sandbox that the Jupyter kernel runs in, so the place to fix this is in `jupyterkernel/cadabra2_jupyter/server.py`. 

I have opened a PR (https://github.com/kpeeters/cadabra2/pull/304) for cadabra2  and will close this issue once it's merged.

Thanks again for flagging this! :+1:

**Comment by inaki-ortizdelandaluce** [comment] 2024-07-28 22:35
Many thanks for following this up providing a PR on the cadabra2 repo already!

**Comment by fjebaker** [comment] 2024-08-02 16:31
Fix has now been merged upstream.

**Closed as completed by fjebaker** 2024-08-02 16:31 UTC
